repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
      - id: black
        alias: black
        name: black
        entry: black --check .
        language: system
        types: [python]
      - id: flake8
        alias: flake8
        name: flake8
        entry: flake8 --ignore=E501 .
        language: system
        types: [ python ]
      - id: isort
        alias: isort
        name: isort
        entry: isort --check .
        language: system
        types: [ python ]
